### ISSUE TITLE
Incompatibility with Python 3.10: SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by mathoudebine** [mathoudebine/homeassistant-timebox-mini#12]
On latest HomeAssistant version using Python 3.10, this service does not work anymore:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/timebox_mini/__init__.py", line 262, in handle_action
    dev.send(conv_image(load_image(dir_path + "/matrices/" + image + ".png")))
  File "/config/custom_components/timebox_mini/timebox.py", line 28, in send
    ret = self.sock.send(bytes(bytearray(package)))
  File "<string>", line 3, in send
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```
This is due to a breaking change that was introduced in Python 3.10 (see [bpo-40943](https://bugs.python.org/issue40943) and [PEP-0353](https://www.python.org/dev/peps/pep-0353/))

This issue has been fixed in pybluez : https://github.com/pybluez/pybluez/issues/426

The problem is that the version of pybluez used by HomeAssistant is too old and cannot be updated because no new official version of pybluez has been made since 2019: https://github.com/pybluez/pybluez/issues/416

Idea to fix it:
- ~~force install latest pybluez from git repository in HomeAssistant: something like `pip install git+https://github.com/pybluez/pybluez` but in HomeAssistant Docker (maybe using a requirements.txt if possible: https://github.com/piksel/pytouch-cube/pull/35/files)~~ does not work because HomeAssistant Docker is not capable of building Python library that does not comes with pre-built wheels: it does not include gcc to build it manually. Only packaged version from PIP contains pre-built wheels.
- ~~force pybluez to a specific commit in `manifest.json` requirements~~ does not work for same reason as above
- **completely remove PyBluez and use generic sockets like** https://github.com/spezifisch/divo/blob/main/divo/bluetooth_socket.py

**Comment by mathoudebine** [comment]
Fixed in release 1.0.2: completely remove PyBluez and use generic sockets
