### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by archit3kt** [mathoudebine/homeassistant-timebox-mini#8]
Hi there,

first thank you for this custom service, It's nice to use my timebox mini with HA ! :)

I'm a new Home Assistant user (coming from Jeedom, I installed HA today, so latest version of everything), followed the Debian 11 install path on virtualbox VM with Sena UD100 bluetooth dongle. Timebox is well connected to the VM, followed all the install instructions (dependencies included) and I can change the display to weather, clock or pictures without issues.

But animations are not working, and the timebox is not responding after the animation command is send to the device. HA log show the following error : 

`2022-03-16 22:53:15 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: illegal image mode
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 367, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 570, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1679, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/timebox_mini/__init__.py", line 314, in handle_action
    for f in load_gif_frames(imagedata):
  File "/config/custom_components/timebox_mini/__init__.py", line 249, in load_gif_frames
    for f in getFrames(imagedata):
  File "/config/custom_components/timebox_mini/__init__.py", line 196, in getFrames
    im.putpalette(p)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 1747, in putpalette
    raise ValueError("illegal image mode")
ValueError: illegal image mode
2022-03-16 22:53:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140698489486304] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 552, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 349, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 367, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 570, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1679, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/timebox_mini/__init__.py", line 314, in handle_action
    for f in load_gif_frames(imagedata):
  File "/config/custom_components/timebox_mini/__init__.py", line 249, in load_gif_frames
    for f in getFrames(imagedata):
  File "/config/custom_components/timebox_mini/__init__.py", line 196, in getFrames
    im.putpalette(p)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 1747, in putpalette
    raise ValueError("illegal image mode")
ValueError: illegal image mode`

Could you please help me resolve this problem ? If you need other informations, please ask me !

Regards

P.S : Super ville Grenoble ! Moi j'ai choisi les Pyrénées ;)

**Comment by mathoudebine** [comment]
Hi and thanks for raising this issue !
I reproduced the bug on my setup
It appears that the behavior of the PIL Python library used to convert gif to timebox pictures has changed in the latest version.
I will fix this in the next version !

Vive les montagnes ;)

**Comment by archit3kt** [comment]
Thank you for your work, much appreciated :)

**Comment by mathoudebine** [comment]
Issue should now be fixed in latest version v1.0.1

**Comment by archit3kt** [comment]
Indeed it is ! Thanks, it works like a charm :)
